### ISSUE TITLE
I need know when open the menu

### ISSUE THREAD

**Issue by lucas-sesti** [huextrat/menu_button#1]
I using your dependency, and i got a problem, i can't know when user open the menu button... or have any way to get this?

**Comment by huextrat** [comment]
I'm working on it, everything should be fine in a few minutes in a new version 0.1.1

**Comment by huextrat** [comment]
@lucas-sesti A new property is now available to know when the menu button is open or not (`onMenuButtonToggle`) in Version 0.1.1+1
Enjoy  !
