### ISSUE TITLE
exceptions on asserts

### ISSUE THREAD

**Issue by sgehrman** [huextrat/menu_button#11]
I was running with "All Exceptions" mode in the VSCode debugger.  

These exceptions fail, and you have the same one twice in a row.

In menu_button.dart

 44:      assert(!dontShowTheSameItemSelected || selectedItem != null),
  45:      assert(!dontShowTheSameItemSelected || selectedItem != null);

**Comment by dipcse07** [comment]
I got the same problem

**Comment by lucas-sesti** [comment]
Are you using the dontShowTheSameItemSelected? (The default value is true, need to add selectedItem option to the Menu Button)

**Comment by dipcse07** [comment]
I am just using only the required values..

**Comment by lucas-sesti** [comment]
Can you show the your menu button code?

**Comment by dipcse07** [comment]
okay wait a second

**Comment by dipcse07** [comment]
@lucas-sesti  I have used same code that has given in the How to use section of menu button in pub.dev just to check everything is okay or not.. but its now working.. with those error message

**Comment by huextrat** [comment]
Ok I can reproduce the issue thanks.
You'll have to pass `selectedItem` property to avoid this kind of error.

And on my side there is a modification to do in the library but it will cause breaking change for current user. I'll try to find a better solution to not require `selectedItem` value

**Comment by lucas-sesti** [comment]
@huextrat If change the dontShowTheSameItem to default false, its the solution i guess

**Comment by huextrat** [comment]
@lucas-sesti Yes that what I'm thinking but all the user using dontShowTheSameItem currently will have to pass it to true after the next update :/

**Comment by huextrat** [comment]
I'm gonna do a new release solving the problem (`1.2.0`) in the afternoon. Thanks for contribution

**Comment by huextrat** [comment]
Please upgrade to `menu_button: 1.2.0` there is a fix for this issue.
