### ISSUE TITLE
Ripple effect not showing on items when decoration.color is set

### ISSUE THREAD

**Issue by WieFel** [huextrat/menu_button#14]
**Is your feature request related to a problem? Please describe.**
When I set the `MenuButton`'s `decoration` to `decoration: BoxDecoration(color: Colors.white)` the ripple effect when clicking an items is not showing. This happens because of this [well-known fact](https://stackoverflow.com/questions/45424621/inkwell-not-showing-ripple-effect). The color of the decoration covers the underlying `InkWell`. When setting no color on the `decoration`, the items are translucent but the ripple effect **does** show. Here is a screenshot of how that looks:

<img width="50%" alt="Simulator Screen Shot - iPhone 12 Pro Max - 2021-02-16 at 10 47 58" src="https://user-images.githubusercontent.com/8345062/108046030-751f3a80-7044-11eb-896f-1741e7bcb4a0.png"/>

**Describe the solution you'd like**
A simple `color` property for the drop-down items that is applied to the parent of the `InkWell` could solve the problem.
E.g. adding a property `itemBackground` to `MenuButton`, then pass it from `MenuButton` to  `_MenuItem<T>` and then within `_MenuItem<T>` do:
```dart
@override
  Widget build(BuildContext context) {
    return Material(
        color: itemBackground,
        child: InkWell(
            onTap: () => Navigator.of(context).pop<T>(value), child: child
        ),
    );
  }
```

**Describe alternatives you've considered**
As described above, omitting decoration color, which didn't help.

**Comment by huextrat** [comment]
Hey @WieFel ! Thank you for your proposal.

Can you please check the PR #16 and confirm to me that it meets your expectations ;)

**Comment by WieFel** [comment]
@huextrat exactly! Thank you very much! ;)

**Comment by huextrat** [comment]
I will try to deliver a 1.3.0 with this change during the day ;)
