### ISSUE TITLE
Issue regarding documentation of the package

### ISSUE THREAD

**Issue by Coder-19** [huextrat/menu_button#18]
Kindly add good documentation for the Menu Button package. Since It is a good alternative to the dropdown button but due to lack of documentation I was stuck in my work for hours. It would be good if example, description and use of each property of the menu button widget could be added in the documentation that would be really good.
Hope next time when I use this then will be able to have good documentation.
Thank you,

**Comment by huextrat** [comment]
I agree on the point of the documentation especially since the package has evolved well over the releases.
I will take some time to make something cleaner and clearer.
Thanks !

**Comment by huextrat** [comment]
- [X] README has been improved
- [ ] Update code documentation

**Comment by Coder-19** [comment]
Thanks

**Comment by Coder-19** [comment]
Thanks, will be waiting for the updated documentation so that I can complete my project faster and on time.

**Comment by huextrat** [comment]
No worries afterwards you can also look at the different examples and understand the code or think for yourself to find your solution !

**Comment by Coder-19** [comment]
ok, hope you do this faster.

**Comment by huextrat** [comment]
I hope you will one day understand the work involved in providing packages and learn how to be polite to ask for changes !

**Comment by Coder-19** [comment]
> I hope you will one day understand the work involved in providing packages and learn how to be polite to ask for changes!

sorry If I was harsh I didn't mean that my main aim was to suggest that some documentation for this package will be good for anyone to understand how to use this wonderful package
once again sorry
