### ISSUE TITLE
I can't scroll childs when dropdown is opened

### ISSUE THREAD

**Issue by lucas-sesti** [huextrat/menu_button#2]
I'm using your dependency, i have a list of numbers to child, 1...12, but, shows just the 1 until 4, and i can't scroll, if my page have a bigger size, i can choose others numbers
I need scroll the list of items..

![image](https://user-images.githubusercontent.com/11727165/79256142-e2c76c80-7e5d-11ea-988b-10867d16dc73.png)
![image](https://user-images.githubusercontent.com/11727165/79256175-ec50d480-7e5d-11ea-8e5d-d17b63f75633.png)

 - Device: iPhone 8
 - OS: iOS 13

**Comment by lucas-sesti** [comment]
I created a new pull request to fixed this problem, look and if is possible, accept, when you merge my changes (or if you prefer change by yourself), i close this issue

**Comment by huextrat** [comment]
Thanks a lot ! I'll be looking at the MR in the next few days.

**Comment by lucas-sesti** [comment]
Thanks!! If you can see the faster possible i will appreciate a lot, because i'm using to job in this week i need upload the final version

**Comment by huextrat** [comment]
@lucas-sesti v0.2.0 is available !

**Comment by lucas-sesti** [comment]
Thanks!!!

**Comment by lucas-sesti** [comment]
Created new pull request because i found an issue, if i create a few items and active the scroll, i can't scroll because the overlay doesn't have height. If you can update in the same urgency last issue, i appreciate a lot.
