### ISSUE TITLE
How do I cancel the built-in border style?

### ISSUE THREAD

**Issue by shaoting0730** [huextrat/menu_button#30]
hello,How do I cancel the built-in border style?

**Comment by u5ele55** [comment]
Hello, @pheromone 
You can provide your own border style with decoration attribute. Instead of "cancelling" border, you can set
```
decoration: BoxDecoration(
  border: Border.all(
    color: Colors.transparent,
  ),
),
```
which will create transparent border around button (notice, that popup with items will also have this transparent border).

**Comment by shaoting0730** [comment]
thank you. @u5ele55
