### ISSUE TITLE
Overlay opening to outside of screen

### ISSUE THREAD

**Issue by lucas-sesti** [huextrat/menu_button#5]
**Describe the bug**
I'm using your dependency but my dropdown button is in the end of screen, and when i open the dropdown, the dropdown open outside of screen, like this: 
![image](https://user-images.githubusercontent.com/11727165/81095093-e38e7400-8eda-11ea-8c6e-d3f4688ffc95.png)

**To Reproduce**
Just put in the end of screen and try open

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS 13.4

When i have free time, i'll try to see this bug and create pull request, but i don't have so much time now, if you have, can you fixed?

**Comment by huextrat** [comment]
I don't have too much time this week but maybe early next week :) I'll keep you informed

**Comment by huextrat** [comment]
@lucas-sesti I'm trying to reproduce the issue but I can't do it when I align the menu_button on the right side of the screen in a stack for example; it's well aligned at the edge.

Can you provide a code to easily reproduce the issue pls ?

**Comment by lucas-sesti** [comment]
Yes, i'll send a piece of code, wait a minute.

**Comment by lucas-sesti** [comment]
```
MenuButton(
          child: button,
          items: _items,
          topDivider: true,
          itemBuilder: (value) => Container(
            alignment: Alignment.center,
            padding: EdgeInsets.fromLTRB(Spacing.base * 3, Spacing.small,
                Spacing.base * 3, Spacing.small),
            child: LjText(
              value,
              options: LjTextOptions.smallCaption,
            ),
            color: Colors.white,
          ),
          toggledChild: Container(
            color: Colors.white,
            child: button,
          ),
          divider: Container(
            height: 1,
            color: theme.dividerColor,
          ),
          onMenuButtonToggle: (btnToggle) {
            // ... action when menu button toggle
          },
          onItemSelected: (value) async {
            // ... my code when my item have been selected
          },
          decoration: BoxDecoration(
              borderRadius: BorderRadius.all(Radius.circular(24.0)),
              color: toggle ? theme.ljGrey[300] : Colors.white,
              boxShadow: [
                BoxShadow(
                    color: Colors.black.withOpacity(.1),
                    offset: Offset(0, 2),
                    blurRadius: 10,
                    spreadRadius: .5)
              ]),
        )
```

and my variable called button:
```
final Widget button = SizedBox(
      width: width,
      height: 40,
      child: Padding(
        padding:
            EdgeInsets.only(left: Spacing.small + 4, right: Spacing.small - 1),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: <Widget>[
            Flexible(
              child: LjText(
                _itemSelecionado, 
                options: LjTextOptions.smallCaption,
                textOverflow: TextOverflow.ellipsis,
              ),
            ),
            FittedBox(
              fit: BoxFit.fill,
              child: Transform.rotate(
                angle: 90 * pi / 180,
                child: Icon(
                  Icons.arrow_forward_ios,
                  size: 12,
                  color: theme.ljGrey[600],
                ),
              ),
            ),
          ],
        ),
      ),
    )
```

And i have an example, its happening when my text is not big enough e.g:
![image](https://user-images.githubusercontent.com/11727165/81245225-d95b9b00-8fea-11ea-89aa-2971fad1e77c.png)

![image](https://user-images.githubusercontent.com/11727165/81245235-e11b3f80-8fea-11ea-8bb9-53fc56929170.png)

And when my option is confirmed:
![image](https://user-images.githubusercontent.com/11727165/81245255-eaa4a780-8fea-11ea-891a-7c129660c983.png)

![image](https://user-images.githubusercontent.com/11727165/81245265-ef695b80-8fea-11ea-8a8f-04092797a77d.png)

**Comment by lucas-sesti** [comment]
Hey, i created new pull request, fixing this issue, if you can see, i'll appreciate
